# -*- coding: utf-8 -*
{
    'name': 'Approval Scenario',
    'author': 'Adarsh',
    'sequence': -1,
    'version': '15.0.00',
    'category': '',
    'summary': 'Approval management system',
    'description': """Approval management system software""",
    'depends': ['base', 'sale', 'hr', 'mail', 'report_xlsx', 'stock'],
    'data': [
        'security/ir.model.access.csv',
        'security/record.xml',
        'data/mail_template.xml',
        'wizard/approval_wizard.xml',
        'wizard/Approve_wizard.xml',
        'wizard/Reject_wizard.xml',
        'views/add_field_project.xml',
        'views/add_states.xml',
        'views/change_group_name.xml',
        'views/sequence_change.xml',
        'views/draft_state.xml',
        'record/report.xml',
        'record/sale_report_inherit.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
